[formatter.nix]
command = "allfmt"
options = ["nix"]
includes = ["*.nix"]

[formatter.oxc]
command = "allfmt"
options = ["oxc"]
includes = ["*.css", "*.json"]

[formatter.sh]
command = "allfmt"
options = ["sh"]
includes = ["*.sh"]

[formatter.toml]
command = "allfmt"
options = ["toml"]
includes = ["*.toml"]
